spring.application.name=hibernate_demo
spring.datasource.url=jdbc:mysql://localhost:3306/telusko_db
spring.datasource.username=root
spring.datasource.password=Nitish@1235

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true